# Generated by Django 6.0.1 on 2026-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='github',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin',
            field=models.CharField(max_length=50),
        ),
    ]
